const ConfigEnvMap = {
  AUTH_SECRET_UUID_OR_SIMILAR: '',
  FACEBOOK_CLIENT_ID: 'FACEBOOK_CLIENT_ID',
  FACEBOOK_CLIENT_SECRET: 'FACEBOOK_CLIENT_SECRET',
  GITHUB_CLIENT_ID: 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET: 'GITHUB_CLIENT_SECRET',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  ROUTE53_USER_ACCESS_KEY: 'ROUTE53_ACCESS_KEY_ID',
  ROUTE53_USER_SECRET_KEY: 'ROUTE53_ACCESS_KEY_SECRET',
  ROUTE53_HOSTED_ZONE_ID: 'ROUTE53_HOSTED_ZONE_ID',
  S3_REGION: 'STORAGE_S3_REGION',
  SMTP_REGION: 'AWS_SMS_REGION',
  SNS_REGION: 'AWS_SMS_REGION',
  S3_USER_ACCESS_KEY: 'STORAGE_AWS_ACCESS_KEY_ID',
  S3_USER_SECRET_KEY: 'STORAGE_AWS_ACCESS_KEY_SECRET',
  SMTP_PASSWORD: 'SMTP_PASS',
  SMTP_USER_ID: 'SMTP_USER',
  SNS_APPLICATION_ID: 'AWS_SMS_APPLICATION_ID',
  SNS_SENDER_ID: 'AWS_SMS_SENDER_ID',
  SNS_USER_ACCESS_KEY: 'AWS_SMS_ACCESS_KEY_ID',
  SNS_USER_SECRET_KEY: 'AWS_SMS_SECRET_ACCESS_KEY'
}

export default ConfigEnvMap
