const Storage = {
  COLOR_MODE: 'COLOR_MODE',
  FORCE_DB_REFRESH: 'FORCE_DB_REFRESH',
  AUTH_SECRET_KEY: 'AUTH_SECRET_UUID_OR_SIMILAR',
  XRENGINE_PATH: 'XRENGINE_PATH',
  PATHS_TABLE: 'paths',
  VARS_TABLE: 'vars'
}

export default Storage
